name: linter

on:
  pull_request:
    branches:
      - main

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: android|ios|node_modules|\.vscode|\.github|\.git|\.expo|\.expo-shared|\.yarn|\.nuxt|\.next|\.idea|\.vscode
